# -*- coding: utf-8 -*-
"""Tomas Otero Lopez - A_notebook_base.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E1Ft05IBkDmS05Dz5Vz1CaBJKrAjhCTa

<div style="background-color:#00843D;padding:22px 28px;border-radius:12px">
  <h2 style="color:white;margin:0;font-size:22px">Analisis Numerico</h2>
  <p style="color:#b8f0c8;margin:6px 0 2px;font-size:14px">Universidad Nacional de Colombia</p>
  <p style="color:#b8f0c8;margin:0;font-size:14px">Prof. Carlos Manuel Orrego Franco</p>
</div>

<div style="background-color:#fff3cd;border-left:5px solid #e67e22;padding:14px 18px;margin-top:12px;border-radius:4px">
  <strong>Actividad en Parejas</strong> &mdash; Entrega: martes 27 de mayo, 11:59 pm<br>
  Elijan <strong>uno</strong> de los dos datasets en la Seccion 1 y ejecuten todo en orden.
</div>

---

# Notebook Base: Neural ODEs sobre Datos Biologicos

## Los dos datasets disponibles

| Opcion | Dataset | Tipo | URL |
|--------|---------|------|-----|
| **A** | Epidemias SIR sinteticas | Biologico sintetico | generado localmente |
| **B** | COVID-19 real por pais | Biologico real | GitHub JHU (verificado) |

## Flujo de trabajo

```
Seccion 1: Elegir y cargar datos
Seccion 2: Explorar y validar
Seccion 3: Configurar hiperparametros  <-- unicos campos que modifican
Seccion 4: Clases de modelos           <-- NO modificar
Seccion 5: Experimentos y tabla comparativa
Seccion 6: Exportar reporte .docx y README.md
```
"""

# Instalar dependencias
import subprocess, sys

for pkg in ["python-docx", "scipy", "scikit-learn"]:
    subprocess.run(
        [sys.executable, "-m", "pip", "install", pkg, "-q"], capture_output=True
    )
print("Dependencias listas.")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import time, os, warnings
from datetime import datetime
from scipy.integrate import solve_ivp
from scipy.optimize import minimize
from scipy.interpolate import CubicSpline
from sklearn.preprocessing import StandardScaler
import tensorflow as tf
from tensorflow import keras
from docx import Document
from docx.shared import Inches, Pt

warnings.filterwarnings("ignore")

plt.rcParams.update(
    {
        "figure.dpi": 120,
        "font.family": "DejaVu Sans",
        "font.size": 11,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "figure.facecolor": "white",
        "axes.facecolor": "#fafafa",
        "axes.grid": True,
        "grid.alpha": 0.3,
    }
)
VERDE = "#00843D"
AZUL = "#1a5fa8"
ROJO = "#c0392b"
NARANJA = "#e67e22"
MORADO = "#8e44ad"
GRIS = "#7f8c8d"

tf.random.set_seed(42)
np.random.seed(42)
print(f"TensorFlow {tf.__version__}  NumPy {np.__version__}")

"""---
## SECCION 1: Elegir y cargar datos

Ejecute **una sola** de las dos celdas siguientes.

"""

# ============================================================
# OPCION B: COVID-19 real por pais (JHU CSSE, GitHub)
# URL verificada: sin registro, acceso directo
# ============================================================
# Datos de casos confirmados de COVID-19 por pais,
# recopilados por Johns Hopkins University CSSE.
# 289 paises x ~1100 dias de observacion diaria.
# Convertimos a muestreo IRREGULAR tomando subconjuntos
# aleatorios de fechas por pais -- simulando el escenario
# real del paper de Rubanova et al. (2019).


URL_JHU = (
    "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/"
    "csse_covid_19_data/csse_covid_19_time_series/"
    "time_series_covid19_confirmed_global.csv"
)

print("Descargando datos COVID-19 (JHU CSSE)...")
try:
    df_jhu = pd.read_csv(URL_JHU)
    print(
        f"Descargado: {df_jhu.shape[0]} paises/regiones x {df_jhu.shape[1] - 4} fechas"
    )
except Exception as e:
    raise RuntimeError(f"Error de descarga: {e}\nVerifique su conexion a internet.")

# Preprocesamiento: agregar por pais, tomar top paises con mejor senal
# Excluir las primeras 4 columnas que son identificadores (Province/State, Country/Region, Lat, Long)
fechas_cols = df_jhu.columns[4:].tolist()
df_pais = df_jhu.groupby("Country/Region")[fechas_cols].sum()

# Calcular nuevos casos diarios (diferencia) -- mas informativa que acumulados
df_nuevos = df_pais.diff(axis=1).fillna(0).clip(lower=0)

# Seleccionar paises con epidemia clara (pico > 500 casos/dia)
pico_max = df_nuevos.max(axis=1)
paises_ok = pico_max[pico_max > 500].index.tolist()
df_sel = df_nuevos.loc[paises_ok]

# Suavizar con ventana de 7 dias y normalizar por pais
df_smooth = df_sel.rolling(window=7, axis=1, min_periods=1).mean()
scaler_covid = StandardScaler()
vals = df_smooth.values.T  # (fechas, paises)
vals_norm = scaler_covid.fit_transform(vals).T  # (paises, fechas)

# Recortar a primeros 500 dias (donde hay mas variabilidad)
N_DIAS = 400
vals_norm = vals_norm[:, :N_DIAS]

# Convertir a formato (n_traj, n_puntos, 1)
data_raw = vals_norm[:, :, np.newaxis].astype("float32")
times_raw = np.linspace(0, 1, N_DIAS, dtype="float32")

NOMBRE_DATASET = "COVID-19 JHU (nuevos casos diarios)"
METODO_CLASICO = "Interpolacion con splines cubicos"
DIM_OBS = 1
VARIABLES = ["Nuevos casos (norm.)"]

print(f"Dataset preparado: {data_raw.shape}  (paises, dias, dims)")
print(f"Paises incluidos: {len(paises_ok)}")
print(f"Muestra de paises: {paises_ok[:8]}")
